// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import "package:firebase_core/firebase_core.dart" show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrDUR-mEOAIiicZKFp4tfToMhjSsEATQU',
    appId: '1:666415558139:web:4bf3be97949c6f6213af5e',
    messagingSenderId: '666415558139',
    projectId: 'seka-ee43b',
    authDomain: 'seka-ee43b.firebaseapp.com',
    storageBucket: 'seka-ee43b.appspot.com',
    measurementId: 'G-JJ24HT7L44',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIIeWnXuBthiXRgW_EFC2pBIMlS4rM1Bw',
    appId: '1:666415558139:android:ef4f10d4362b63e613af5e',
    messagingSenderId: '666415558139',
    projectId: 'seka-ee43b',
    storageBucket: 'seka-ee43b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCl1luEQz26sNC4qHrHMCFOyCvEYLfFS3M',
    appId: '1:666415558139:ios:406d1b84f634344113af5e',
    messagingSenderId: '666415558139',
    projectId: 'seka-ee43b',
    storageBucket: 'seka-ee43b.appspot.com',
    iosBundleId: 'com.example.sekaa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCl1luEQz26sNC4qHrHMCFOyCvEYLfFS3M',
    appId: '1:666415558139:ios:406d1b84f634344113af5e',
    messagingSenderId: '666415558139',
    projectId: 'seka-ee43b',
    storageBucket: 'seka-ee43b.appspot.com',
    iosBundleId: 'com.example.sekaa',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBrDUR-mEOAIiicZKFp4tfToMhjSsEATQU',
    appId: '1:666415558139:web:de44c2c4500ac55713af5e',
    messagingSenderId: '666415558139',
    projectId: 'seka-ee43b',
    authDomain: 'seka-ee43b.firebaseapp.com',
    storageBucket: 'seka-ee43b.appspot.com',
    measurementId: 'G-96GLDGEGM1',
  );
}
